In [1]:
import torch
torch.__version__


'2.3.0+cpu'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# check dims
scalar.ndim

0

In [4]:
# retrieve number from tensor
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

1

In [8]:
# Check vector shape
vector.shape

torch.Size([2])

In [9]:
# Matrix
# lower case for scalar and vector, UPPER case for MATRIX and TENSOR
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# matrices have an extra dimension over 
MATRIX.ndim

2

In [11]:
# 2 elements deep and 2 wide
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# check dimensions, can count # of brackets for # of dims
TENSOR.ndim

3

In [14]:
# 1 dimension of 3 x 3
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9575, 0.6142, 0.1144, 0.9413],
         [0.9293, 0.8415, 0.3160, 0.6220],
         [0.2328, 0.6958, 0.4001, 0.1722]]),
 torch.float32)

In [16]:
# Create a random tensor to match common image shape [224, 224, 3] ([height, width, color channel])
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
# Create tensor full of zeros, can be useful for masking values to let a model know not to learn them
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [18]:
# Create all ones tensor, similar purpose as zeros
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [19]:
# torch arange function to create ranges
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# use _like function with ones or zeros to create tensors of said number with same shape as input
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# many datatypes for tensors, more precise math = slower to compute
# default datatype is float32 (32 bit decimal)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is either torch32 or whatever dtype is passed in
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on tensor are recorded

float_32_tensor, float_32_tensor.dtype, float_32_tensor.device
# Common errors with pytorch arise from mismatched tensor dtypes or devices 
# (pytorch likes for tensor operations to share dtypes and be on the same device)


(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [24]:
# tensor with dtype=float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # equivalent to torch.half

float_16_tensor.dtype

torch.float16