In [1]:
import torch
torch.__version__


'2.3.0+cpu'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# check dims
scalar.ndim

0

In [4]:
# retrieve number from tensor
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

1

In [6]:
# Check vector shape
vector.shape

torch.Size([2])

In [7]:
# Matrix
# lower case for scalar and vector, UPPER case for MATRIX and TENSOR
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
# matrices have an extra dimension over 
MATRIX.ndim

2

In [9]:
# 2 elements deep and 2 wide
MATRIX.shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
# check dimensions, can count # of brackets for # of dims
TENSOR.ndim

3

In [12]:
# 1 dimension of 3 x 3
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2684, 0.3463, 0.8876, 0.6814],
         [0.0858, 0.0806, 0.5547, 0.6368],
         [0.7429, 0.4212, 0.3831, 0.7118]]),
 torch.float32)

In [14]:
# Create a random tensor to match common image shape [224, 224, 3] ([height, width, color channel])
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
# Create tensor full of zeros, can be useful for masking values to let a model know not to learn them
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
# Create all ones tensor, similar purpose as zeros
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [17]:
# torch arange function to create ranges
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# use _like function with ones or zeros to create tensors of said number with same shape as input
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# many datatypes for tensors, more precise math = slower to compute
# default datatype is float32 (32 bit decimal)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is either torch32 or whatever dtype is passed in
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on tensor are recorded

float_32_tensor, float_32_tensor.dtype, float_32_tensor.device
# Common errors with pytorch arise from mismatched tensor dtypes or devices 
# (pytorch likes for tensor operations to share dtypes and be on the same device)


(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [20]:
# tensor with dtype=float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # equivalent to torch.half

float_16_tensor.dtype

torch.float16

In [21]:
# Getting information from tensors

# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")



tensor([[0.7334, 0.6333, 0.6138, 0.0472],
        [0.7921, 0.9584, 0.1719, 0.9743],
        [0.0480, 0.9707, 0.8147, 0.8034]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
# Manipulating tensors
# Basic operations

# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [23]:
# Multiply it by 10
tensor * 10


tensor([10, 20, 30])

In [24]:
# Tensors don't change values unless they are reassigned 
tensor

tensor([1, 2, 3])

In [25]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)



tensor([110, 120, 130])

In [29]:
# does not change original tensor
tensor

tensor([11, 12, 13])

In [31]:
# Element-wise multiplication (each element multiplies its equivalent, index 0 -> 0, 1-> 1, 2 ->2)
print(tensor, "*", tensor)
print("Equals", tensor * tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals tensor([121, 144, 169])


In [1]:
# Matrix Multiplication 
# inner dimensions must match
# @ is python symbol for matrix multiplication
# (# of rows, # of cols)
# (3, 2) @ (3, 2) won't work
# (2, 3) @ (3, 2) will work
# (3, 2) @ (2, 3) will 
# result has shape of out dims
# (2, 3) @ (3, 2) -> (2, 2)
# (3, 2) @ (2, 3) -> (3, 3)

import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
# Element wise multiplication 
# calculation ->  [1*1, 2*2, 3*3] = [1, 4, 9]
# code -> tensor * tensor

# Matrix multiplication
# calculation [1*1 + 2*2 + 3*3] = [14] 
# code -> tensor.matmul(tensor)

In [2]:
# Element wise multiplication 
tensor * tensor

tensor([1, 4, 9])

In [3]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Shape mismatch is one of the most common errors in deep learning

tensor_A = torch.tensor([1, 2],
                        [3, 4]
                        [5, 6], dtype=torch.float32)

tensor_B = torch.tensor([7, 10],
                        [8, 11]
                        [9, 12], dtype=torch.float32)

# This won't work, inner dims don't match 